#!/usr/bin/env bash
#
# Install everything!

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

fancy_echo() {
  echo "\n$1"
}

fancy_echo "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update

fancy_echo "Installing git ..."
  brew install git
#  brew install git-flow

fancy_echo "Installing Postgres ..."
  brew install postgres --no-python
  ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents/
  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
  rm -rf /usr/local/var/postgres/*
  initdb /usr/local/var/postgres -E utf8
  createuser -s postgres

fancy_echo "Installing Redis ..."
 brew install redis
 ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents/
 launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist

fancy_echo "Installing neovim ..."
  brew install neovim

fancy_echo "Installing fzf"
  brew install fzf

fancy_echo "Installing ripgrep"
  brew install ripgrep

fancy_echo "Installing vundle ..."
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

# fancy_echo "Installing GNU Compiler Collection ..."
#  brew tap homebrew/dupes
#  brew install apple-gcc42

# fancy_echo "Upgrading and linking OpenSSL ..."
#  brew install openssl

# TODO update
# install this manually for now
fancy_echo "Installing asdf, Language version manager ..."
  # Update to latest version
  # git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.4.3

fancy_echo "Installing Elixir ..."
  asdf plugin-add elixir
  asdf install elixir

fancy_echo "Installing node.js ..."
  asdf plugin-add nodejs
  asdf install nodejs

fancy_echo "Installing diff-so-fancy ..."
  brew install diff-so-fancy

fancy_echo "Done! Now you need to manually install the following: "
fancy_echo "- https://github.com/ferd/erlang-history"
