#!/usr/bin/env bash
#
# Basic setup for a new Mac
#
# DO THIS FIRST: Install XCode, start it, and accept the ToS.

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

fancy_echo() {
  echo "\n$1"
}

fancy_echo "Installing Homebrew ..."
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew update

fancy_echo "Installing all the Homebrew things..."
brew install \
  git \
  postgres \
  redis \
  neovim \
  fzf \
  ripgrep \
  diff-so-fancy \
  erlang \
  watchman \
  openssl \
  coreutils \
  automake \
  autoconf \
  libyaml \
  readline \
  libxslt \
  libtool \
  unixodbc

fancy_echo "Setting up Postgres..."
  brew services start postgresql
  initdb /usr/local/var/postgres -E utf8
  createuser -s postgres

fancy_echo "Setting up Redis..."
  brew services start redis

fancy_echo "Installing vundle..."
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle

fancy_echo "Installing asdf, Language version manager..."
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.0
  echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
  echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc

fancy_echo "Installing Elixir..."
  asdf plugin-add elixir
  asdf install elixir 1.7.4

fancy_echo "Installing node.js..."
  asdf plugin-add nodejs
  NODEJS_CHECK_SIGNATURES=no asdf install nodejs 8.12.0


fancy_echo "Installing global node packages..."
  npm -g i stylelint ember-cli prettier tslint eslint typescript

fancy_echo "Done! Restart your terminal for changes to take effect."
